name: 'Run unittests'
description: 'Runs unittests'
inputs:
  python_path:
    description: 'PYTHONPATH for test to find source code'
    required: true
  tests_path:
    description: 'path for unittest to discover tests'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set pythonpath
      shell: bash
      run: |
        echo "PYTHONPATH=${{ inputs.python_path }}:$PYTHONPATH" >> $GITHUB_ENV

    - name: Run unit tests
      shell: bash
      run: |
        python -m unittest discover -s ${{ inputs.tests_path }} -t ${{ inputs.tests_path }}