name: 'Run unittests'
description: 'Runs unittests'
inputs:
  python_path:
    description: 'PYTHONPATH for tests to run'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set pythonpath
      shell: bash
      run: |
        echo "PYTHONPATH=${{ inputs.python_path }}:$PYTHONPATH" >> $GITHUB_ENV

    - name: Run unit tests
      shell: bash
      run: |
        python -m unittest discover -s ./api/tests/test_scripts/unit_tests -t ./api/tests/test_scripts/unit_tests
