name: 'Run unittests'
description: 'Runs unittests'
runs:
  using: "composite"
  steps:
    # Add api/endpoints to PYTHONPATH to resolve imports
    - name: Set pythonpath
      shell: bash
      run: |
        echo "PYTHONPATH="./api/tests/test_scripts:./api/endpoints:./api/tests"" >> $GITHUB_ENV
    - name: Run unit tests
      shell: bash
      run: |
        python -m unittest api.tests.test_scripts.unit_tests.test_user_group  
